import { ThemeModeScript } from "flowbite-react";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Providers } from "../store/provider";

import Header from "../components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${inter.className} bg-gray-100`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
