import { Inter } from "next/font/google";
import "../styles/globals.css";
import PrelineScript from "../components/PrelineScript";
import { Providers } from "../store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <Providers>{children}</Providers>
      </body>
      <PrelineScript />
    </html>
  );
}
